services:
  ros:
    build: .
    container_name: ros_container
    working_dir: /home/dv1_ws
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - ros_network
    volumes:
      - ./dv1_ws:/home/dv1_ws
      - ./rosbag1:/home/rosbag1
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: ["/home/dv1_ws/start.sh"]

networks:
  ros_network:
    driver: bridge

